/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ghost;

import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Ryan
 */
public class GhostUI extends javax.swing.JFrame {

    private Game game;

    /**
     * Creates new form GhostUI
     */
    public GhostUI(Game game) {
        initComponents();
        setup();
        this.game = game;
        this.game.addObserver(new GameObserver());
    }

    private class GameObserver implements Observer {

        @Override
        public void update(Observable o, Object arg) {
            currDisplay.setText(game.currWord);
            if (game.winner == -1) {
                if (game.currMover.equals("User")) {
                    status.setText("User's Turn.");
                } else {
                    status.setText("Computer's Turn.");
                    game.compMove();
                }
            } else {
                String winnerText = "";
                if (game.winStatus == 0) {
                    winnerText += "Invalid word. ";
                } else if (game.winStatus == 1) {
                    winnerText += "No valid word longer than 3 letters can be extended from this word. ";
                } else {
                    winnerText += "Word completed. ";
                }

                if (game.winner == 0) {
                    winnerText += "User wins.";
                } else {
                    winnerText += "Computer wins.";
                }

                status.setText(winnerText);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ghostLabel = new javax.swing.JLabel();
        currLabel = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        enterLabel = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        newGame = new javax.swing.JButton();
        currDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ghostLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ghostLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ghostLabel.setText("GHOST");

        currLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        currLabel.setText("CURRENT WORD:");

        status.setText("User's Turn.");

        enterLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        enterLabel.setText("ENTER LETTER:");

        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        newGame.setText("New Game");

        currDisplay.setBackground(new java.awt.Color(255, 255, 255));
        currDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currDisplay.setText("Enter a character.");
        currDisplay.setBorder(new javax.swing.border.MatteBorder(null));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, currDisplay, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(144, 144, 144)
                        .add(status))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(currLabel))
                    .add(layout.createSequentialGroup()
                        .add(152, 152, 152)
                        .add(ghostLabel))
                    .add(layout.createSequentialGroup()
                        .add(99, 99, 99)
                        .add(enterLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(input, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(131, 131, 131)
                        .add(newGame)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(ghostLabel)
                .add(10, 10, 10)
                .add(currLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(currDisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(status)
                        .add(29, 29, 29))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(input, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(enterLabel)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(newGame)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        char c = input.getText().charAt(0);
        game.move(c);
    }//GEN-LAST:event_inputActionPerformed

    /**
     * @param args the command line arguments
     */
    private void setup() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GhostUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GhostUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GhostUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GhostUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currDisplay;
    private javax.swing.JLabel currLabel;
    private javax.swing.JLabel enterLabel;
    private javax.swing.JLabel ghostLabel;
    private javax.swing.JTextField input;
    private javax.swing.JButton newGame;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}